auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("listings/<int:id>", views.listing, name="listing"),
    path("listings/create", views.create_listing, name="create_listing"),
    path("category", views.category, name="category"),
    path("category/<int:id>", views.category_listing, name="category_listing"),
    path("watchlist", views.watchlist_view, name="watchlist"),
    path("watchlist/<int:listing_id>", views.watchlist, name="handle_watchlist"),
    path("listings/<int:listing_id>/comment", views.comment, name="comment"),
    path("bid/<int:listing_id>", views.bid, name="bid"),
    path("close/<int:listing_id>", views.close, name="close"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django import forms
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    pass


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Listing(models.Model):
    title = models.CharField(max_length=65)
    description = models.TextField()
    starting_price = models.FloatField()
    image_url = models.URLField(null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name="listings", blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(default=timezone.now)
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="listings")
   

    def __str__(self):
        return f"{self.title} - {('Active' if self.is_active else 'Inactive' )}"
    
    def get_current_price(self):
        bid = self.bids.order_by("amount").last()
        current_price = self.starting_price if not bid else bid.amount
        return current_price
       



class Bid(models.Model):
    bidder = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="bids")
    amount = models.FloatField()
    

    def __str__(self):
        return f"Bid on {self.listing.title} by {self.bidder.username} for {self.amount}"
    


class Comment(models.Model):
    writer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="comments")
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.writer.username} on {self.listing.title}"


class Watchlist(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='watchlist')
    listing = models.ForeignKey(
        Listing, on_delete=models.CASCADE, related_name="watchlist")
    def __str__(self):
        return f"{self.user.username} interested in {self.listing.title}"

auctions/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import User, Listing, Bid, Comment, Category, Watchlist
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, "auctions/index.html", {"listings": Listing.objects.filter(is_active=True)})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def category(request):
    return render(request, "auctions/category.html", {"categories": Category.objects.all()})


def category_listing(request, id):
    return render(request, "auctions/category_listing.html", {"listings": Listing.objects.filter(category=id), "category": Category.objects.get(id=id)})


def listing(request, id):
    requested_listing = Listing.objects.get(id=id)
    current_bid = requested_listing.bids.order_by("amount").last()

    try:
        watchlist = Watchlist.objects.get(listing=requested_listing, user=request.user)
        is_in_watchlist = True
    except:
        is_in_watchlist = False

    return render(request, 'auctions/listing.html', {"listing": requested_listing, "watchlist": is_in_watchlist, "current_bid":current_bid})


@login_required
def create_listing(request):
    if request.method == "POST":
        title = request.POST["title"]
        description = request.POST["description"]
        starting_price = request.POST["starting_price"]
        img_url = request.POST["image_url"]
        category_name = request.POST["category"]

        try:
            category = Category.objects.get(name=category_name)
        except Category.DoesNotExist:
            category = None

       
        seller = request.user
        listing = Listing(title=title, description=description, starting_price=starting_price,
                          image_url=img_url, category=category, seller=seller)
        listing.save()

        starting_bid = Bid(bidder=seller, listing=listing, amount=starting_price)
        starting_bid.save()

        return redirect("listing", listing.id)

    else:
        return render(request, "auctions/listing_form.html", {"categories": Category.objects.all()})


@login_required
def watchlist_view(request):
    user = request.user
    watchlist_items = Watchlist.objects.filter(user=user)
    listings = [item.listing for item in watchlist_items]
    return render(request, "auctions/watchlist.html", {"listings": listings})


@login_required
def watchlist(request, listing_id):
    user = request.user
    listing = Listing.objects.get(id=listing_id)

    try:
        watchlist_item = Watchlist.objects.get(user=user, listing=listing)
        watchlist_item.delete()
        messages.success(request, "removed from watchlist")
    except Watchlist.DoesNotExist:
        Watchlist.objects.create(user=user, listing=listing)
        messages.success(request, "added to watchlist")

    return HttpResponseRedirect(reverse("listing", args=[listing_id]))


@login_required
def bid(request,  listing_id):
    user_id = request.user.id
    if request.method == 'POST':

        listing = Listing.objects.get(id=listing_id)

        if not listing.is_active:
            messages.error(request, "This listing is not active.")
            return HttpResponseRedirect(reverse("listing", args=[listing_id]))

        try:
            bidder = User.objects.get(id=user_id)
            price = request.POST["price"]
            highest_bid = Bid.objects.filter(
                listing=listing).order_by("amount").last()

            if not price:
                price = "0"

            if price.replace(".", "", 1).isdigit():
                price = float(price)
            else:
                raise ValueError("Your input is invalid, try again :)")

            if price > highest_bid.amount:
                listing.bids.create(bidder=bidder, listing=listing, amount=price)
            else:
                raise ValueError(
                    f'Your bid price should be greater than ${highest_bid.amount}')
        except ValueError as e:
            messages.error(request, str(e))

        return HttpResponseRedirect(reverse("listing", args=[listing_id]))


@login_required
def close(request, listing_id):
    user= request.user

    listing = Listing.objects.get(id=listing_id)
    if listing.seller.id == user.id:
        if not listing.is_active:
            messages.error(request, "The listing is already closed.")
            return HttpResponseRedirect(reverse("listing", args=[listing_id]))

        listing.is_active = False
        listing.save()
        
        messages.success(request, "The listing is closed.")
        return HttpResponseRedirect(reverse("index"))

    messages.error(request, "You are not allowed to close this listing.")
    return HttpResponseRedirect(reverse("listing", args=[listing_id]))


@login_required
def comment(request, listing_id):
    if request.method == "POST":
        writer = User.objects.get(id=request.user.id)
        listing = Listing.objects.get(id=listing_id)
        Comment.objects.create(
            writer=writer, content=request.POST["content"], listing=listing)

        return HttpResponseRedirect(reverse("listing", args=[listing_id]))

    else:
        return HttpResponseRedirect(reverse("listing", args=[listing_id]))

auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <h2> Listing Categories</h2>
    <ul>
        {% for category in categories %}
          <li>
            <a href="{% url 'category_listing' category.id %}">{{ category.name }}</a>
          </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

auctions/templates/auctions/category_listing.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <h2> {{category.name}} Category </h2>
  {% for listing in listings %}
    {% include "auctions/listing_item.html" with listing=listing %}
  {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="container">
    <h2>Active Listing</h2>
  {% for listing in listings %}
    {% include "auctions/listing_item.html" with listing=listing %}
  {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
             <li class="nav-item">
                    <a class="nav-link" href="{% url 'category' %}">Categories</a>
                </li>
            {% if user.is_authenticated %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}


{% block body %}

<!-- feedback messages -->
{% include 'auctions/messages.html' %}

<div class="container">
    <div class="row mb-3">
        <div class="col-md-8">
        <!-- listing details -->
          <h2>Listing: {{ listing.title }}</h2>

          {% if listing.image_url %}
              <img src="{{ listing.image_url }}" alt="{{ listing.title }}" width="500px" height="300px">
          {% else %}
              <img src="https://placehold.co/500x300" alt="Default Image" >
          {% endif %}

          <p>{{ listing.description }}</p>

          <h6>Details:</h6>
          <ul>
              <li> listed by {{ listing.seller.username  }}</li>
              <li> Category: 
                  {% if listing.category %}
                    {{listing.category.name }}
                  {% else %}
                     No Category listed 
                  {% endif %}
              </li>
          </ul>

          <h5>Price: ${{ listing.get_current_price }} </h5>
        </div>  
    </div>
        <!-- buttons -->
        <div class="row border-bottom">
          <div class="col my-3">
            {% if user.id == listing.seller.id %}
              <button type="button" class="btn btn-danger btn-sm"><a href="{% url 'close' listing_id=listing.id %}" style="color: white; text-decoration: none;">Close Auction</a></button>
            {% endif %}

            {% if watchlist %}
              <button type="button" class="btn btn-primary btn-sm"> <a href="{% url 'handle_watchlist' listing.id %}" style="color: white; text-decoration: none;">remove from watchlist</a></button>
            {% else %}
              <button type="button" class="btn btn-primary btn-sm"> <a href="{% url 'handle_watchlist'  listing.id %}" style="color: white; text-decoration: none;">add to watchlist</a></button>
            {% endif %}
          </div>
        </div>  
   
   
   <!-- bids form -->
   <div class="row my-3">
      <div class="col">
          {% if listing.is_active %}
          {{listing.bids.all|length}} bid(s) so far. 
          {% if listing.bids.all|length > 0 and user == current_bid.bidder %}
              Your bid is the current bid.
          {% endif %}
          {% else %}
              {% if listing.bids.all|length > 0 and user == current_bid.bidder %}
              Congratulations! You are the winner.
              {% else %}
              Closed.
              {% endif %}
          {% endif %}
      </div> 
   </div>


  <div class="row border-bottom">
      <div class="col">
          <form action="{% url 'bid' listing_id=listing.id %}" method="post" >
              <div class="form-group">
                  <input type="text" placeholder="Bid" name="price" class="form-control">
              </div>
              <button type="submit" class="btn btn-primary btn-sm mb-2">Place Bid</button>
          {% csrf_token %}
          </form>
      </div>
  </div>
   
   <!-- comments section-->
   <div class="row mt-4">
     <div class="col-12">
        <h3>Comments</h3>
        {% for comment in listing.comments.all %}
        <div>
            <p><strong>{{ comment.writer.username }}:</strong> {{ comment.content }}</p>
            <p class="text-muted">{{ comment.created_at}}</p>
        </div>
      
        {% endfor %}
     </div>
   </div>
   
   <!-- comment form -->
   <div class="row">
      <div class="col">
        <form action="{% url 'comment' listing_id=listing.id %}" method="post" >
        {% csrf_token %}
            <div class="form-group">
              <label for="comment">Your comment:</label>
              <textarea  name="content" id="comment" class="form-control" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Post</button>
        </form>
      </div>
    </div>

</div>

{% endblock %}

auctions/templates/auctions/listing_form.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Create New Listing</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'create_listing' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_title">Title:</label>
            <input type="text" id="id_title" name="title" class="form-control" placeholder="Enter title" required>
        </div>

        <div class="form-group">
            <label for="id_description">Description:</label>
            <textarea id="id_description" name="description" class="form-control" placeholder="Enter description" required></textarea>
        </div>

        <div class="form-group">
            <label for="id_starting_price">Starting Price:</label>
            <input type="number" id="id_starting_price" name="starting_price" class="form-control" placeholder="Enter starting price" required>
        </div>

        <div class="form-group">
            <label for="id_image_url">Image URL:</label>
            <input type="url" id="id_image_url" name="image_url" class="form-control" placeholder="Enter image URL">
        </div>
        
        <div class="form-group">
            <label for="id_category">Category:</label>
            <select id="id_category" name="category" class="form-control">
                <option value="">---------</option>
                {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>

        <input class="btn btn-primary" type="submit" value="Create Listing">
    </form>

{% endblock %}

auctions/templates/auctions/listing_item.html
  <div class="row mb-3 border"> 
      <div class="col-12">
        <div class="d-flex align-items-center"> 
          {% if listing.image_url %}
            <img src="{{ listing.image_url }}" alt="{{ listing.title }}" style="width: 200px; height: 200px; margin-right: 20px;"> <!-- Adjust dimensions as needed -->
          {% else %}
            <img src="https://placehold.co/200" alt="Default Image" style="width: 200px; height: auto; margin-right: 20px;">
          {% endif %}
          
          <div>
            <h2><a href="{% url 'listing' listing.id %}">{{ listing.title }}</a></h2>
            <p><strong>Price:</strong> $ {{ listing.get_current_price }}</p> 
            <p>{{ listing.description }}</p>
            <p><small>Created {{ listing.created_at }}</small></p>
          </div>
        </div>
      </div>
    </div>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/messages.html
{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
        {% if message.tags == "error"%}
            <div class="alert alert-danger" role="alert">
        {% else %}
            <div class="alert alert-{{ message.tags }}" role="alert">
        {% endif %}
        {{ message }}
            </div>
    {% endfor %}
{% endif %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="container">
    <h2>My watchlist</h2>
  {% for listing in listings %}
    {% include "auctions/listing_item.html" with listing=listing %}
  {% endfor %}
</div>


{% endblock %}